var app=getApp();
Page({
    data:{
        info:[
            {
                time:'2016.09.20',
                time1:'13.30',
                message:'【嘉定】嘉定的派件已签收，感谢您使用中通快递！'
            },{
                time:'2016.09.20',
                time1:'13.30',
                message:'【嘉定】嘉定的派件已签收，感谢您使用中通快递！'
            },{
                time:'2016.09.20',
                time1:'13.30',
                message:'【嘉定】嘉定的派件已签收，感谢您使用中通快递！'
            },{
                time:'2016.09.20',
                time1:'13.30',
                message:'【嘉定】嘉定的派件已签收，感谢您使用中通快递！'
            },
        ],
        gswl:{
            img:'../../image/icon64_appwx_logo.png',
            name:'中通',
            message:'409509087777'
        }
    }
})